export const siteData = {
  identity: {
    title: "鸦珉.icu",
    subtitle: "一张稍微不太正经的项目地图",
  },
  projects: [
    {
      id: "coffee-sleep",
      order: 10,
      visible: true,
      variant: "large",
      icon: "coffee",
      title: "睡前剩几杯",
      status: "已上线",
      statusTone: "live",
      description: "11点睡觉时，体内还剩几杯咖啡？",
      url: "https://coffeesleep.cn/",
      urlLabel: "coffeesleep.cn",
    },
    {
      id: "pojian",
      order: 20,
      visible: true,
      variant: "large",
      icon: "leaf",
      title: "破茧",
      status: "建设中",
      statusTone: "building",
      description: "每天 3 分钟，看见算法之外的世界。",
      url: "https://pojian.space/",
      urlLabel: "pojian.space",
    },
    {
      id: "rough-cut",
      order: 30,
      visible: true,
      variant: "wide",
      icon: "video",
      title: "视频粗剪工具",
      status: "计划中",
      statusTone: "plan",
      description: "快速粗剪，节省时间。",
      url: "",
      urlLabel: "",
    },
    {
      id: "social-app",
      order: 40,
      visible: true,
      variant: "wide",
      icon: "phone",
      title: "社交媒体方向 App",
      status: "计划中",
      statusTone: "plan",
      description: "探索更有意思的社交应用形态。",
      url: "",
      urlLabel: "",
    },
    {
      id: "more-lab",
      order: 50,
      visible: true,
      variant: "wide",
      icon: "cube",
      title: "更多实验位",
      status: "先空着",
      statusTone: "quiet",
      description: "空着也很好，至少不会乱。",
      url: "",
      urlLabel: "",
    },
  ],
  todos: [
    {
      id: "v1-page",
      order: 10,
      visible: true,
      title: "整理 V1",
      tone: "green",
      progress: 68,
    },
    {
      id: "links",
      order: 20,
      visible: true,
      title: "补链接",
      tone: "orange",
      progress: 45,
    },
    {
      id: "domain",
      order: 30,
      visible: true,
      title: "域名稳定",
      tone: "blue",
      progress: 54,
    },
    {
      id: "project-wheel",
      order: 40,
      visible: true,
      title: "3D 项目轮",
      tone: "purple",
      progress: 32,
    },
  ],
  thoughts: [
    {
      id: "why-exist",
      order: 10,
      visible: true,
      text: "不确定为什么存在",
      tone: "green",
    },
    {
      id: "hatching",
      order: 20,
      visible: true,
      text: "正在孵化",
      tone: "blue",
    },
    {
      id: "not-company",
      order: 30,
      visible: true,
      text: "不是公司官网",
      tone: "purple",
    },
    {
      id: "leave-it",
      order: 40,
      visible: true,
      text: "先放着",
      tone: "orange",
    },
  ],
  channels: [
    {
      id: "bilibili",
      order: 10,
      visible: true,
      title: "哔哩哔哩",
      tone: "pink",
      url: "https://space.bilibili.com/15068209",
    },
    {
      id: "youtube",
      order: 20,
      visible: true,
      title: "YouTube",
      tone: "red",
      url: "https://www.youtube.com/@yamin-vio1in",
    },
    {
      id: "daily-pojian",
      order: 30,
      visible: true,
      title: "今日破茧",
      tone: "blue",
      url: "https://space.bilibili.com/3493267880544550",
    },
    {
      id: "wechat-video",
      order: 40,
      visible: false,
      title: "视频号",
      tone: "green",
      url: "",
    },
  ],
};
