export const siteData = {
  identity: {
    title: "鸦珉.icu",
    subtitle: "一张不太正经的项目地图",
  },
  projects: [
    {
      id: "pojian",
      order: 10,
      visible: true,
      variant: "large",
      icon: "newspaper",
      title: "破茧",
      status: "已上线",
      statusTone: "live",
      description: "每天 3 分钟，看见算法之外的世界。",
      url: "https://pojian.space/",
      urlLabel: "pojian.space",
    },
    {
      id: "coffee-sleep",
      order: 20,
      visible: true,
      variant: "large",
      icon: "coffee",
      title: "睡前剩几杯",
      status: "已上线",
      statusTone: "live",
      description: "11点睡觉时，体内还剩几杯咖啡？",
      url: "https://coffeesleep.cn/",
      urlLabel: "coffeesleep.cn",
    },
    {
      id: "placeholder-03",
      order: 30,
      visible: true,
      variant: "wide",
      icon: "cube",
      title: "空白卡片 03",
      status: "空位",
      statusTone: "quiet",
      description: "这里先留给下一个冒出来的东西。",
      url: "",
      urlLabel: "",
    },
    {
      id: "placeholder-04",
      order: 40,
      visible: true,
      variant: "wide",
      icon: "cube",
      title: "空白卡片 04",
      status: "待命",
      statusTone: "quiet",
      description: "如果暂时没想好，也可以先不假装想好了。",
      url: "",
      urlLabel: "",
    },
    {
      id: "placeholder-05",
      order: 50,
      visible: true,
      variant: "wide",
      icon: "cube",
      title: "空白卡片 05",
      status: "备用",
      statusTone: "quiet",
      description: "一张备用卡，等以后有东西住进来。",
      url: "",
      urlLabel: "",
    },
  ],
  todos: [
    {
      id: "rough-cut",
      order: 10,
      visible: true,
      title: "视频粗剪工具",
      tone: "red",
      progress: 5,
    },
    {
      id: "social-app",
      order: 20,
      visible: true,
      title: "社交媒体方向 App",
      tone: "blue",
      progress: 0,
    },
    {
      id: "project-wheel",
      order: 30,
      visible: true,
      title: "主页项目区3D轮更新",
      tone: "white",
      progress: 0,
    },
    {
      id: "todo-mpw5cc13",
      order: 40,
      visible: false,
      title: "新的待办",
      tone: "black",
      progress: 0,
    },
    {
      id: "todo-mpw5cc7t",
      order: 50,
      visible: false,
      title: "新的待办",
      tone: "blue",
      progress: 0,
    },
  ],
  thoughts: [
    {
      id: "why-exist",
      order: 10,
      visible: true,
      text: "被看见的成本",
    },
    {
      id: "hatching",
      order: 20,
      visible: true,
      text: "被信任的成本",
    },
    {
      id: "not-company",
      order: 30,
      visible: true,
      text: "被选择的成本",
    },
    {
      id: "leave-it",
      order: 40,
      visible: true,
      text: "“关我屁事，我是商人”",
    },
    {
      id: "thought-mpw4svho",
      order: 50,
      visible: true,
      text: "产品做出来了，然后呢？",
    },
    {
      id: "thought-mpw5iiya",
      order: 60,
      visible: true,
      text: "联盟营销",
    },
    {
      id: "thought-mpw5iocm",
      order: 70,
      visible: true,
      text: "广告变现",
    },
    {
      id: "thought-mpw77tq8",
      order: 80,
      visible: true,
      text: "AI革命",
    },
    {
      id: "thought-mpw7k05p",
      order: 90,
      visible: true,
      text: "Welcome.",
    },
    {
      id: "thought-mpwbq1op",
      order: 100,
      visible: true,
      text: "社会贡献",
    },
    {
      id: "thought-mpwbxu4e",
      order: 110,
      visible: true,
      text: "社群",
    },
  ],
  channels: [
    {
      id: "bilibili",
      order: 10,
      visible: true,
      title: "哔哩哔哩",
      tone: "pink",
      url: "https://space.bilibili.com/15068209",
    },
    {
      id: "youtube",
      order: 20,
      visible: true,
      title: "YouTube",
      tone: "red",
      url: "https://www.youtube.com/@yamin-vio1in",
    },
    {
      id: "daily-pojian",
      order: 30,
      visible: true,
      title: "今日破茧",
      tone: "blue",
      url: "https://space.bilibili.com/3493267880544550",
    },
    {
      id: "wechat-video",
      order: 40,
      visible: false,
      title: "视频号",
      tone: "green",
      url: "",
    },
  ],
};
